name: Run Trading Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '58 8 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Trading Bot
      env:
        ANGEL_CLIENT_CODE: ${{ secrets.ANGEL_CLIENT_CODE }}
        ANGEL_PIN: ${{ secrets.ANGEL_PIN }}
      run: |
        python main.py
